### ISSUE TITLE
Great idea, but didn't work

### ISSUE THREAD

**Issue by mushon** [mscodemonkey/Sketch-Find-And-Replace#1]
This is (potentially) a great time saver, but I couldn't get it to work not even on the simplest document. See?

![screencast](http://g.recordit.co/RYG8y2DvOj.gif)

**Comment by mscodemonkey** [comment]
Yeah, sorry about that, i'd left the part that does the whole document scope commented out!  Now works fine and have tested with your exact example.

**Comment by mushon** [comment]
Confirmed. Works like a charm. Thanks!
