### ISSUE TITLE
Can’t be blank?

### ISSUE THREAD

**Issue by julians** [mscodemonkey/Sketch-Find-And-Replace#10]
Hello,

I’ve got lots of labels like this: ‘55 points’ and want them to read ‘55’, i. e. remove the ‘ points’. I’d expect this to work if I search for the phrase ‘ points’ and leave the replacement field blank, but all I get is a popup telling me that find or replace can’t be blank.

Is there a workaround or would you consider adding this feature?

Thanks,
Julian

**Comment by Mco-Design** [comment]
Same as Julians: I want to remove characters but cannot as I also get the message _"Find or replace cannot be blank"_

**Comment by idoshavit** [comment]
requesting as well

**Comment by moeffju** [comment]
#11 was now merged
