### ISSUE TITLE
Erasing line breaks

### ISSUE THREAD

**Issue by barts** [mscodemonkey/Sketch-Find-And-Replace#2]
Hi, I just tried this plugin with a text box that had a line break and then a line of text that started with "How to". So I tried to find/replace it with the words "Learn to" and it replaced the "How to" but also erased the preceding line break. I would have expected it to ignore the line break and only replace the text I wanted replaced?

**Comment by barts** [comment]
This video shows what I'm talking about: http://cl.ly/3S2L1y2j3X2A . All the text jumps up a line after I do the replace because line break got erased.

**Comment by mscodemonkey** [comment]
Fixed this - was trimming the result where it didn't need to
