### ISSUE TITLE
Can't replace Chinese strings

### ISSUE THREAD

**Issue by Nat30** [mscodemonkey/Sketch-Find-And-Replace#27]
Somehow, the plugin can't find Chinese strings and be replace to Chinese strings.

**Comment by seandellis** [comment]
I was able to get it replace a single character, but I didn't test it any further.

Be sure to check **Case sensitive**. See the attached image for reference.

![screenshot 2017-05-18 01 11 33](https://cloud.githubusercontent.com/assets/1584916/26188862/35ee7300-3b67-11e7-977f-7597596bb5fd.png)

**Comment by seandellis** [comment]
Dupe of #7

**Comment by Nat30** [comment]
@seandellis It's working after i check yes. Thanks a lot.
