### ISSUE TITLE
Changing Colors 

### ISSUE THREAD

**Issue by mischugo** [mscodemonkey/Sketch-Find-And-Replace#3]
Hello, would it be nice to have the choice about changing colors like Adobe Fireworks does :-)
Find: ededed - Replace with: 000000 and all objects with this light grey will change to black

Or, on more detail/choice - only objects (not text elements)

Best, Maik

**Comment by mscodemonkey** [comment]
Well really this is a text find and replace plugin and there are other plugins that already do this for object properties but I might look into adding this in future so i'll leave it open.
